# Change baseurl before deploy
baseurl = "https://ash0lam.github.io/"
languageCode = "en-us"
title = "Omakase by Ash"

# Theme i18n support
defaultContentLanguage = "en"
hasCJKLanguage = false

# Disqus 設定
disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 5

enableRobotsTXT = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
  date = ["date", "publishDate", ":default"]

[time]
 timeZone = "Asia/Hong_Kong"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # ✅ 允許 Hugo 解析 <iframe> 這類 HTML
  [markup.highlight]
    style = "dracula"  # ✅ 選擇語法高亮的風格

[params]
  showReadingTime = false
  description = "No fixed menu. Human ideas, sparked by curiosity — shaped with AI into real solutions."