# Change baseurl before deploy
baseurl = "https://ash0lam.github.io/"
languageCode = "en-us"
title = "Omakase by Ash"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 5

enableRobotsTXT = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
  date = ["date", "publishDate", ":default"]

[time]
  location = "Asia/Hong_Kong"

[markup]
  [markup.date]
    format = "Jan 02, 2006 15:04 MST"

[params]
  showReadingTime = false

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true