backend:
  name: git-gateway
  branch: main  # 你的 GitHub 分支名稱

media_folder: "static/images/uploads"  # 圖片上傳目錄
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "封面圖片", name: "cover", widget: "image" }
      - { label: "內容", name: "body", widget: "markdown" }
